### ISSUE TITLE
Python version error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [ekusiadadus/pychatgpt-tutorial#1]
When I tried to install this repository, the following error occurred.

```
$ poetry install

Current Python version (3.8.10) is not allowed by the project (^3.10).
Please change python executable via the "env use" command.
```

Is python version allowd just for 3.10?

**Comment by Ishihara-Masabumi** [comment]
When I tried to install chatgptpy, the following error occurred.

```
$ pip3 install chatgptpy --upgrade
ERROR: Could not find a version that satisfies the requirement chatgptpy (from versions: none)
ERROR: No matching distribution found for chatgptpy
```
Please let me know the version that satisfies the requirement chatgptpy.

**Comment by ekusiadadus** [comment]
@Ishihara-Masabumi 

No, python version allowed is specified in the project's [pyproject.toml](https://github.com/ekusiadadus/pychatgpt-tutorial/blob/master/pyproject.toml) file. 

When I tried to use version 3.9, I was able to successfully install this repository. (But I did not try 3.8)

As of [PyChatGPT](https://github.com/rawandahmad698/PyChatGPT/blob/master/pyproject.toml), it uses Python 3.9.

**Comment by Ishihara-Masabumi** [comment]
I installed pyenv and made the environment of python 3.10.0b3.
Then, I tried to install this repository.
But, the following error occurred, despite I set the gmail adress and password.

```
$ poetry run python3 main.py
>> Tracking conversation enabled.
>> Access Token missing or expired. Attempting to create them...
[OpenAI] Email address: ********@gmail.com
[OpenAI] Password: ********
[OpenAI] Beginning auth process
[OpenAI][1] Making request to https://chat.openai.com/auth/login
Traceback (most recent call last):
  File "/home/dl/chatgptpy/pychatgpt-tutorial/main.py", line 10, in <module>
    chat = Chat(email="maty0505@gmail.com", password="masabumi", options=options)
  File "/home/dl/.cache/pypoetry/virtualenvs/pychatgpt-tutorial-gA4kcLC1-py3.10/lib/python3.10/site-packages/pychatgpt/main.py", line 50, in __init__
    self._setup()
  File "/home/dl/.cache/pypoetry/virtualenvs/pychatgpt-tutorial-gA4kcLC1-py3.10/lib/python3.10/site-packages/pychatgpt/main.py", line 139, in _setup
    self._create_access_token()
  File "/home/dl/.cache/pypoetry/virtualenvs/pychatgpt-tutorial-gA4kcLC1-py3.10/lib/python3.10/site-packages/pychatgpt/main.py", line 157, in _create_access_token
    openai_auth.create_token()
  File "/home/dl/.cache/pypoetry/virtualenvs/pychatgpt-tutorial-gA4kcLC1-py3.10/lib/python3.10/site-packages/pychatgpt/classes/openai.py", line 133, in create_token
    raise Exceptions.Auth0Exception("Failed to make the first request, Try that again!")
pychatgpt.classes.exceptions.Auth0Exception: Failed to make the first request, Try that again!
```

Please tell me what's the matter.

**Comment by ekusiadadus** [comment]
@Ishihara-Masabumi 
Currently, ChatGPT provides their apis only for subscribed users. 
Please check here.

https://chat.openai.com/auth/login
